version: 2.0.{build}
branches:
 only:
   - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
skip_commits:
  message: /(Created|Update).*\.(png|jpg|jpeg|bmp|gif|md)/
environment:
    SONAR_TOKEN: 
        secure: b45J8d8RnM19gldF3sJX6UGacdYRXvyTYpubf1YUrGdHXZi+90NOtstyftjLXMSO
dotnet_csproj: 
  patch: true 
  file: '**\*.csproj' 
  version: '{version}' 
  package_version: '{version}' 
  assembly_version: '{version}' 
  file_version: '{version}' 
  informational_version: '{version}' 
before_build:
- cmd: nuget restore
- cmd: choco install opencover.portable
- cmd: choco install codecov
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
build_script:
 - dotnet tool install --global dotnet-sonarscanner
 - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet 
 sonarscanner begin /k:"guibranco_ViaCEP" 
 /d:sonar.organization="guibranco-github" 
 /d:sonar.host.url="https://sonarcloud.io" 
 /d:sonar.login="$env:SONAR_TOKEN" /v:"$env:APPVEYOR_BUILD_NUMBER" 
 /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" 
 /d:sonar.coverage.exclusions="ViaCEP.Tests/**,**/*Tests.cs" 
 /d:sonar.cs.opencover.reportsPaths="$env:CD\ViaCEP.Tests\coverage.opencover.xml" }'
 - dotnet build
 - ps: dotnet test .\ViaCEP.Tests\ViaCEP.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat="opencover"
 - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner end /d:sonar.login="$env:SONAR_TOKEN" }'
 - codecov -f "ViaCEP.Tests\coverage.opencover.xml"
after_build:
- xcopy %CD%\ViaCEP\bin\Release\netstandard2.0\*.* %CD%\src\
- xcopy %CD%\ViaCEP\bin\Release\ViaCEP.%APPVEYOR_BUILD_VERSION%.nupkg %CD%\src\
- rd /s /q %CD%\ViaCEP\bin\Release\
- cd %CD%
- 7z a -tzip -mx9 "ViaCEP.v%APPVEYOR_BUILD_VERSION%.zip" src
artifacts:
- path: ViaCEP.v%APPVEYOR_BUILD_VERSION%.zip
  name: ZipFile
- path: ViaCEP.%APPVEYOR_BUILD_VERSION%.nupkg
  name: Package
deploy:
- provider: Environment
  name: NuGet
  artifact: Package
- provider: GitHub
  tag: $(appveyor_build_version)
  auth_token:
    secure: VgYYJdvNLy/n9/uxxlaF0bMpIIrVxCb+dGr66U9nWfPWSN2ySdfuilO8klAw0uvF
  force_update: true
  artifact: ZipFile